### ISSUE TITLE
Crash in "The Legend of Zelda: Tears of the Kingdom"

### ISSUE THREAD

**Issue by senden9** [flathub/org.yuzu_emu.yuzu#1073]
### yuzu Version

1441

### Description

Crashed when running around in the "Marak-gutsi-shrine" while holding caring a sonor device with my ultra-hand. Could not reproduce.

### Reproduction Certainty

Rarely

### System Information

```bash session
System:
  Host: XXXXXXXX Kernel: 6.2.0-20-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 44.0 Distro: Ubuntu 23.04 (Lunar Lobster)
Machine:
  Type: Laptop System: Dell product: XPS 15 9510 v: N/A
    serial: <superuser required>
  Mobo: Dell model: XXXXXXXX v: A01 serial: <superuser required> UEFI: Dell
    v: 1.19.0 date: 03/10/2023
Battery:
  ID-1: BAT0 charge: 70.1 Wh (100.0%) condition: 70.1/84.3 Wh (83.1%)
    volts: 12.6 min: 11.4 model: SMP DELL XXXXXXXX status: full
  Device-1: ps-controller-battery-00:01:6c:c8:66:d0 model: N/A charge: N/A
    status: full
CPU:
  Info: 8-core model: 11th Gen Intel Core i9-11900H bits: 64 type: MT MCP
    arch: Tiger Lake rev: 1 cache: L1: 640 KiB L2: 10 MiB L3: 24 MiB
  Speed (MHz): avg: 2409 high: 2500 min/max: 800/4800:4900 cores: 1: 2500
    2: 2500 3: 2500 4: 2500 5: 2500 6: 1046 7: 2500 8: 2500 9: 2500 10: 2500
    11: 2500 12: 2500 13: 2500 14: 2500 15: 2500 16: 2500 bogomips: 79872
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel TigerLake-H GT1 [UHD Graphics] vendor: Dell driver: i915
    v: kernel arch: Gen-12.1 bus-ID: 0000:00:02.0
  Device-2: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile] vendor: Dell
    driver: nvidia v: 525.105.17 arch: Ampere bus-ID: 0000:01:00.0
  Device-3: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo
    bus-ID: 1-11:3
  Display: wayland server: X.Org v: 1.22.1.8 with: Xwayland v: 22.1.8
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa dri: iris gpu: i915
    resolution: 3440x1440~100Hz
  API: OpenGL v: 4.6 Mesa 23.0.2 renderer: Mesa Intel UHD Graphics (TGL GT1)
    direct-render: Yes
Network:
  Device-1: Intel Tiger Lake PCH CNVi WiFi vendor: Rivet Networks
    driver: iwlwifi v: kernel bus-ID: 0000:00:14.3
  IF: wlp0s20f3 state: down mac: cc:15:31:22:9e:f3
  Device-2: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152
    bus-ID: 6-2.4:4
  IF: enxa02919ce3e27 state: up speed: 1000 Mbps duplex: full
    mac: XXXXXXXX
  IF-ID-1: docker0 state: down mac: XXXXXXXX
  IF-ID-2: mpqemubr0 state: down mac: XXXXXXXX
  IF-ID-3: virbr0 state: down mac: XXXXXXXX
  IF-ID-4: virbr1 state: down mac: XXXXXXXX
Drives:
  Local Storage: total: 953.87 GiB used: 364.52 GiB (38.2%)
Info:
  Processes: 430 Uptime: 3h 53m Memory: 62.51 GiB used: 4.3 GiB (6.9%)
  Init: systemd target: graphical (5) Compilers: gcc: 12.2.0 clang: 15.0.7
  Packages: 3727 Shell: Zsh v: 5.9 inxi: 3.3.25
```

### Logs and Backtraces

[yuzu_log.txt.old(1).txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/11649930/yuzu_log.txt.old.1.txt)

### Remarks

This is the first crash i noticed.

**Comment by MooneMan** [comment]
Get rid of the numbers in the names of your update, DLC, and game files. They don't seem to be yours and you could get banned.

**Comment by MooneMan** [comment]
>Shader <Warning> shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp:CollectStorageBuffers:392: Storage buffer failed to track, using global memory fallbacks

>Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xa58f1b3589305fd6
>Shader <Warning> shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp:CollectStorageBuffers:395: Storage buffer tracked without bias, index 6 offset 0

You seem to have some issues with your shaders. I had these same lines and clearing the vulkan pipeline cache worked for me. Have you tried that?

**Comment by senden9** [comment]
Thanks for that remark.

The bug happens super rare. Like every two days. If it happens then the moment when I crash a Zonai Device into something.

I cleared the shader cache just now. If the bug happens again I can report again. If it will not re-trigger till the end of the week I will close that issue and assume that clearing the cache solved the problem.

**Comment by senden9** [comment]
The bug did never reappear. It seams clearing the vulkan pipeline cache did solve the occurrence of that bug.
