### ISSUE TITLE
Can't use GNOME theme

### ISSUE THREAD

**Issue by MightyCreak** [flathub/org.yuzu_emu.yuzu#169]
I can't get the GNOME theme when using the flatpak package.

Here's how it looks like with Flatpak:
![image](https://user-images.githubusercontent.com/6382548/137602398-9a20f5a2-fc5b-487a-854b-76a5c17dc727.png)

Here's how it looks like with a local build (much cleaner and it adapt to the system preference):
![image](https://user-images.githubusercontent.com/6382548/137602413-f72b60d1-7451-46d2-bd73-77bea0fbd57d.png)

I tried to install these two runtime packages:
- org.kde.PlatformTheme.QGnomePlatform (v5.15)
- org.kde.KStyle.Adwaita (v5.15)

But it didn't work either.

**Comment by Mershl** [comment]
Hi @MightyCreak,

The KDE runtime received some theming fixes that should fix exactly this. Can you still reproduce the issue?

**Comment by MightyCreak** [comment]
@Mershl I have the 808 right now and it's a bit better but not exactly seamless (see the tabs background and the OK/Cancel buttons):

![Screenshot 2021-11-13 20-52-58](https://user-images.githubusercontent.com/6382548/141664434-99aecc59-a45f-441a-9d43-30d51a18b5cd.png)

**Comment by Mershl** [comment]
Yep. That's the current state of the KDE runtime theming on a Gnome host. There's been some discussion on #flatpak, it's getting a bit traction - yuzu flatpak can't do very much itself.

**Comment by MightyCreak** [comment]
If it's the best we can do right now, I'm ok with closing this issue. At least it gets the pre-defined OS theme, as it does when ran locally!

**Comment by liushuyu** [comment]
So can I close this issue for now?

**Comment by MightyCreak** [comment]
Depends.. if the code is as good as it can be and it's just a matter of Flatpak/GNOME/KDE to sync together, then yes yuzu can't do more and you can close this issue.

But if other KDE applications using Flatpak can have the full GNOME theme, then it must be something yuzu could do.

**Comment by liushuyu** [comment]
> Depends.. if the code is as good as it can be and it's just a matter of Flatpak/GNOME/KDE to sync together, then yes yuzu can't do more and you can close this issue.
> 
> But if other KDE applications using Flatpak can have the full GNOME theme, then it must be something yuzu could do.

I think this is the best we could do. Even under KDE, the theme does not look right since the Flatpak uses a sandbox and the theme is "intimidated" from the host.

**Comment by MightyCreak** [comment]
"intimidated" ?

**Comment by liushuyu** [comment]
> "intimidated" ?

Sorry, "imitate". My software keyboard auto-corrected the word to something it thought was correct.

**Comment by MightyCreak** [comment]
Ok then let's close this issue!
