### ISSUE TITLE
Yuzu Flatpak distributable missing toolbar

### ISSUE THREAD

**Issue by sanecito** [flathub/org.yuzu_emu.yuzu#178]
(moving from https://github.com/yuzu-emu/yuzu/issues/7215 at suggestion of maintainer)

**Issue:** Yuzu doesn't show the toolbar that contains menu items like 'File'

**Solutions/Workarounds Tried:** Pressing Alt or Ctrl M but those hotkeys to show toolbar don't reveal it

**How to replicate:**

1. Install Yuzu [via Flathub](https://flathub.org/apps/details/org.yuzu_emu.yuzu)
2. Open Yuzu
3. Validate toolbar is missing

![image](https://user-images.githubusercontent.com/3056597/138543711-d44b3025-8c31-4f51-aa38-660c236d5902.png)

Example of how Yuzu should appear with the toolbar:

![image](https://user-images.githubusercontent.com/3056597/138543858-c37a563a-2007-4b6b-b748-c06c74dd4643.png)

**System Info:**

Yuzu Version: Yuzu 787
Operating System: Fedora KDE 34
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.14.13-200.fc34.x86_64 (64-bit)
Graphics Platform: X11

**Comment by liushuyu** [comment]
Is this still the case with Yuzu mainline 820 or later?

**Comment by liushuyu** [comment]
Ping? Are you still experiencing this issue in the current version?

**Comment by sanecito** [comment]
Now seems fixed. Specs for reference:

Yuzu 845

Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.6-200.fc35.x86_64 (64-bit)
