### ISSUE TITLE
[flatpak-specific] SSBU ultimate attacks using h264 backgrounds segfault Yuzu with GPU Video Decoding (Default)

### ISSUE THREAD

**Issue by Mershl** [flathub/org.yuzu_emu.yuzu#200]
## Description
SSBU ultimate attacks (e.g. Sepiroth's ultimate) play a h264 video in the background. While NVDEC emulation is set to `GPU Video Decoding (Default)` yuzu segfaults when trying to create such background. Appimage does not show this issue.

## Workaround
Setting NVDEC emulation to `CPU only` immediatly fixes the issue.

## Interesting log lines of the crash
```
[ 157.685752] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:SetTargetCodec:166: NVDEC video codec initialized to H264
[ 157.691127] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:CreateGpuAvDevice:74: Using VA-API with i915
[libopenh264 @ 0x7e94fc0f9440] [OpenH264] this = 0x0x7e94fd428dc0, Warning: max_num_ref_frames exceeds level limits!
```

Seems like Flatpak Yuzu tries to init VAAPI with i915 (the Intel driver) on an AMDGPU system.

**Comment by Mershl** [comment]
My first guess was `--devices=dri`, which unfortunately does not easily fix the issue.

**Comment by Mershl** [comment]
Found a second game with the same crash: `FATAL FRAME: Maiden of Black Water`.

The game uses a h264 background in the main menu. It crashes once the intro logos have been played.

**Comment by liushuyu** [comment]
> Seems like Flatpak Yuzu tries to init VAAPI with i915 (the Intel driver) on an AMDGPU system.

Yes. Yuzu will try to initialize `ffmpeg` decoder with a kernel driver in this order:

```
i915
iHD
amdgpu
```

Normally, `ffmpeg` should report initialization failed when an incompatible driver is selected. But in this case, `ffmpeg` reported success when Yuzu was trying `i915` driver. 

I will investigate this issue, I suspected this is a Yuzu bug. You probably did not encounter this issue using the AppImage version or natively compiled version because you did not install an Intel driver in your system (but Flatpak runtime bundled an Intel driver inside the base image).

**Comment by liushuyu** [comment]
A workaround is being worked on: https://github.com/yuzu-emu/yuzu/pull/7431

**Comment by liushuyu** [comment]
You can help me verify if my workaround is working: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-978916311

**Comment by Mershl** [comment]
Hi @liushuyu,

the test build is based on yuzu-mainline 777 (bit older). Is that expected?

**Comment by liushuyu** [comment]
> Hi @liushuyu,
> 
> the test build is based on yuzu-mainline 777 (bit older). Is that expected?
> 

No, this is not expected. I have corrected this mistake now.

> EDIT: SSBU crashes when going in a match in testbuild:
> 

 Sigh. This still looks like software decoding was used. I have tried another workaround to make Flatpak use a more complete `ffmpeg` binary instead of the watered-down version it currently uses.

**Comment by liushuyu** [comment]
A new test build is available: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-979542913

Please install `org.freedesktop.Platform.ffmpeg-full` before using it. Due to an issue in Flatpak, I can't make this as a dependency and automatically download this full version of FFmpeg in the update.

**Comment by Mershl** [comment]
Hi @liushuyu,

your fix is working nicely. Both crashes in SSBU and Fatal Frame are no longer reproduciable. The h264 played in the SSBU backgrounds seem a slight bit too fast - but that could be just me and is topic for a different discussion.

#### Using
```
flatpak list | grep "ffmpeg\|yuzu"
ffmpeg-full	org.freedesktop.Platform.ffmpeg-full		21.08	flathub	system
Yuzu	org.yuzu_emu.yuzu	mainline-0-826	test	yuzu-origin	user
```
#### SSBU
```
[ 193.594901] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:SetTargetCodec:209: NVDEC video codec initialized to H264
[ 193.601084] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:CreateGpuAvDevice:114: Using VA-API with amdgpu
[h264 @ 0x7f26d416f2c0] Increasing reorder buffer to 1
[ 194.453919] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:505: 0x595a1c0df7c85727
[ 194.454169] Shader <Warning> shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp:Read:143: (STUBBED) SR_WSCALEFACTOR_XY
[ 194.454180] Shader <Warning> shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp:Read:146: (STUBBED) SR_WSCALEFACTOR_Z
[ 194.454198] Shader <Warning> shader_recompiler/frontend/ir/ir_emitter.cpp:GetFlowTest:265: (STUBBED) FCSM_TR
[h264 @ 0x7f26d416f2c0] Increasing reorder buffer to 2
[ 200.571567] Service.NVDRV <Info> core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:OnClose:68: NVDEC video stream ended
[ 200.577764] Service.NVDRV <Info> core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:OnClose:68: NVDEC video stream ended
```

#### Fatal Frame
```
[  31.774758] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():219: Assertion Failed!
texture format=5 srgb=false components={7 4 2 2}
[  31.779226] Debug <Critical> video_core/texture_cache/format_lookup_table.cpp:operator():219: Assertion Failed!
texture format=5 srgb=false components={7 4 2 2}
[  33.008969] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:SetTargetCodec:209: NVDEC video codec initialized to H264
[  33.024586] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:CreateGpuAvDevice:114: Using VA-API with amdgpu
[  33.063230] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl.cpp:IocCtrlEventRegister:178: Event already registered! Unregistering previous event
[  33.971845] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl.cpp:IocCtrlEventRegister:178: Event already registered! Unregistering previous event
[  55.233892] Service.NVDRV <Info> core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:OnClose:68: NVDEC video stream ended
[  55.235970] Service.NVDRV <Info> core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:OnClose:68: NVDEC video stream ended
[  55.922022] HW.GPU <Error> video_core/texture_cache/image_base.cpp:AddImageAlias:187: Compressed to compressed image aliasing is not implemented
```

**Comment by Mershl** [comment]
> Please install org.freedesktop.Platform.ffmpeg-full before using it. Due to an issue in Flatpak, I can't make this as a dependency and automatically download this full version of FFmpeg in the update.

AFAIK this only affects test builds. The final publish can include the dependency and will install it on update.

**Comment by liushuyu** [comment]
> > Please install org.freedesktop.Platform.ffmpeg-full before using it. Due to an issue in Flatpak, I can't make this as a dependency and automatically download this full version of FFmpeg in the update.
> 
> AFAIK this only affects test builds. The final publish can include the dependency and will install it on update.

Thank you, the changes have been merged in Yuzu upstream and should be available in the next mainline/EA release.

**Comment by liushuyu** [comment]
Could you try this build: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-981354966 to see whether it breaks on AMD GPUs? Thanks!

**Comment by liushuyu** [comment]
If a fix is confirmed, I think we can close this issue.

**Comment by Mershl** [comment]
Using test build referenced in https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-981354966.

Both reproducers are fixed. SSBU goes in match. No other regressions found.
