### ISSUE TITLE
Missing BOOT0 - Missing BCPKG2-1-Normal-Main - Missing PRODINFO

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.yuzu_emu.yuzu#211]
![Captura de tela de 2021-11-20 17-06-22](https://user-images.githubusercontent.com/26097419/142739599-72f0721e-a73e-4245-b572-a471e2295574.png)
```
Gtk-Message: 17:06:02.067: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:06:02.067: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
```

**Comment by liushuyu** [comment]
This is expected. Most games require encryption keys to boot. You can dump them from your Switch by following this guide. https://yuzu-emu.org/help/quickstart/#dumping-prodkeys-and-titlekeys

**Comment by liushuyu** [comment]
I think I will close this issue as this is not a Yuzu or Flatpak version of the Yuzu issue.
