### ISSUE TITLE
Unable to use GPU Video decoding

### ISSUE THREAD

**Issue by firig43** [flathub/org.yuzu_emu.yuzu#218]
This might be an issue with the runtime, but I'll report it here since it affects yuzu.

Driver: NVIDIA 495.44

Yuzu always fallback to cpu video decoding and further investigation revealed that ffmpeg shipped with kde/freedesktop runtime does not support nvdec/nvenc. 

No luck with vdpau, can't find any useful doc online.

**Comment by liushuyu** [comment]
Ugh, audio/video decoding is such a disaster in Flatpak.

Also, see #200, the decoder does not work on AMD as well. I will try to find a workaround for this issue.

**Comment by liushuyu** [comment]
A workaround is being worked on: https://github.com/yuzu-emu/yuzu/pull/7431

**Comment by liushuyu** [comment]
You can help me verify if my workaround is working: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-978916311

**Comment by firig43** [comment]
```
[  35.352629] Config <Info> common/settings.cpp:operator():34: Renderer_NvdecEmulation: 2
...
[  54.822532] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:SetTargetCodec:205: NVDEC video codec initialized to VP9
...
[  54.841762] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:Initialize:197: Using FFmpeg software decoding
```
Sad

**Comment by liushuyu** [comment]
> 

Can you post the full log as an attachment here?

**Comment by firig43** [comment]
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/7607431/yuzu_log.txt)

**Comment by liushuyu** [comment]
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/7607431/yuzu_log.txt)

It seems like I made a mistake in the last build.

A new test build is available: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-979542913

Please install `org.freedesktop.Platform.ffmpeg-full` before using it. Due to an issue in Flatpak, I can't make this as a dependency and automatically download this full version of FFmpeg in the update.

**Comment by firig43** [comment]
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/7609918/yuzu_log.txt)
```
Freedesktop Platform      org.freedesktop.Platform               21.08.5           21.08      flathub     system
i386                      org.freedesktop.Platform.Compat.i386                     21.08      flathub     system
Mesa                      org.freedesktop.Platform.GL.default    21.1.8            20.08      flathub     system
Mesa                      org.freedesktop.Platform.GL.default    21.2.5            21.08      flathub     system
nvidia-495-44             …freedesktop.Platform.GL.nvidia-495-44                   1.4        flathub     system
default                   org.freedesktop.Platform.GL32.default                    21.08      flathub     system
nvidia-495-44             …eedesktop.Platform.GL32.nvidia-495-44                   1.4        flathub     system
ffmpeg-full               org.freedesktop.Platform.ffmpeg-full                     21.08      flathub     system
openh264                  org.freedesktop.Platform.openh264      2.1.0             2.0        flathub     system
```

**Comment by liushuyu** [comment]
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/7609918/yuzu_log.txt)
> 
> ```
> Freedesktop Platform      org.freedesktop.Platform               21.08.5           21.08      flathub     system
> i386                      org.freedesktop.Platform.Compat.i386                     21.08      flathub     system
> Mesa                      org.freedesktop.Platform.GL.default    21.1.8            20.08      flathub     system
> Mesa                      org.freedesktop.Platform.GL.default    21.2.5            21.08      flathub     system
> nvidia-495-44             …freedesktop.Platform.GL.nvidia-495-44                   1.4        flathub     system
> default                   org.freedesktop.Platform.GL32.default                    21.08      flathub     system
> nvidia-495-44             …eedesktop.Platform.GL32.nvidia-495-44                   1.4        flathub     system
> ffmpeg-full               org.freedesktop.Platform.ffmpeg-full                     21.08      flathub     system
> openh264                  org.freedesktop.Platform.openh264      2.1.0             2.0        flathub     system
> ```

I see. It seems like this is more complicated than I anticipated. Flatpak sandbox is not very NVIDIA friendly, although I will try to find some other workarounds.

**Comment by liushuyu** [comment]
Could you try this build: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-981354966 ?

**Comment by firig43** [comment]
Checked again, seems like gpu video decoding does not work with native build as well, so it's probably related to my system(fedora 35, vdpau is available according to vdpauinfo). 

It does work on my alt system(debian 11) tho, notable differences between them are lib placement(most libs on fedora are located at /lib64) and no native ffmpeg on my fedora installation.

**Comment by liushuyu** [comment]
> Checked again, seems like gpu video decoding does not work with native build as well, so it's probably related to my system(fedora 35, vdpau is available according to vdpauinfo).
> 

Some games may use a video format that `VDPAU` could not handle (VP8). Also, Flatpak does not have `VDPAU` installed in its sandboxed environment, so that's out of the question.

> It does work on my alt system(debian 11) tho, notable differences between them are lib placement(most libs on fedora are located at /lib64) and no native ffmpeg on my fedora installation.

Library folder placement is irrelevant in our case (for Flatpak, it does not use the libraries on your host system). For native build: on Fedora, you might want to add the [RPMFusion repository](https://rpmfusion.org/Configuration/) (you only need to enable the `free` repository) to get `ffmpeg` onto your system.

**Comment by firig43** [comment]
[#221 log](https://github.com/flathub/org.yuzu_emu.yuzu/files/7633666/yuzu_log.txt)

**Comment by liushuyu** [comment]
> [#221 log](https://github.com/flathub/org.yuzu_emu.yuzu/files/7633666/yuzu_log.txt)

Sorry, this seems to be taking longer than anticipated to fix. I am currently trying to come up with a fix to avoid breaking non-NVIDIA GPU.

**Comment by liushuyu** [comment]
Here is a new build that hopefully should fix your issue: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-985952000
This build bundled a copy of FFmpeg that supports CUDA decoding.

**Comment by firig43** [comment]
Worked, but yuzu is using vdpau instead of cuda(vp9).

**Comment by liushuyu** [comment]
> Worked, but yuzu is using vdpau instead of cuda(vp9). Edit: looks like the ffmpeg shipped with build 74058 simply doesn't have cuda support.
> 
> ```
> [📦 org.yuzu_emu.yuzu ~]$ ffmpeg -hwaccels
> ffmpeg version 4.3.3 Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 11.2.0 (GCC)
>   configuration: --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --disable-debug --disable-doc --disable-static --enable-optimizations --enable-shared --disable-everything --enable-ffplay --enable-ffprobe --enable-gnutls --enable-libaom --enable-libdav1d --enable-libfdk-aac --enable-libmp3lame --enable-libfontconfig --enable-libfreetype --enable-libopus --enable-libpulse --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-openal --enable-opengl --enable-sdl2 --enable-vulkan --enable-zlib --enable-libv4l2 --enable-libxcb --enable-vdpau --enable-vaapi --enable-encoder='ac3,alac,flac,libfdk_aac,g723_1,mp2,libmp3lame,libopus,libspeex,pcm_alaw,pcm_mulaw,pcm_f32le,pcm_s16be,pcm_s24be,pcm_s16le,pcm_s24le,pcm_s32le,pcm_u8,tta,libvorbis,wavpack,' --enable-encoder='ass,ffv1,libaom_av1,libvpx_vp8,libvpx_vp9,mjpeg_vaapi,rawvideo,theora,vp8_vaapi,libopenh264' --enable-decoder='adpcm_g722,alac,flac,g723_1,g729,libfdk_aac,libopus,libspeex,mp2,mp3,m4a,pcm_alaw,pcm_mulaw,pcm_f16le,pcm_f24le,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_s16be,pcm_s16be_planar,pcm_s24be,pcm_s16le,pcm_s16le_planar,pcm_s24le,pcm_s24le_planar,pcm_s32le,pcm_s32le_planar,pcm_s64be,pcm_s64le,pcm_s8,pcm_s8_planar,pcm_u8,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,tta,vorbis,wavpack,' --enable-decoder='ass,ffv1,mjpeg,mjpegb,libaom_av1,libdav1d,libvpx_vp8,libvpx_vp9,rawvideo,theora,vp8,vp9,libopenh264' --enable-encoder='bmp,gif,jpegls,png,tiff,webp,' --enable-decoder='bmp,gif,jpegls,png,tiff,webp,' --enable-hwaccel='vp8_vaapi,mjpeg_vaapi,' --enable-parser='aac,ac3,flac,mjpeg,mpegaudio,mpeg4video,opus,vp3,vp8,vp9,vorbis,' --enable-muxer='ac3,ass,flac,g722,gif,matroska,mp3,mpegvideo,rtp,ogg,opus,pcm_s16be,pcm_s16le,wav,webm,' --enable-demuxer='aac,ac3,ass,flac,g722,gif,image_jpeg_pipe,image_png_pipe,image_webp_pipe,matroska,mjpeg,mov,mp3,mpegvideo,ogg,pcm_mulaw,pcm_alaw,pcm_s16be,pcm_s16le,rtp,wav,' --enable-filter='crop,scale,overlay,amix,amerge,aresample,format,aformat,fps,transpose,pad,' --enable-protocol='crypto,file,pipe,rtp,srtp,rtsp,tcp,udp,unix,' --arch=x86_64 --enable-libopenh264
>   libavutil      56. 51.100 / 56. 51.100
>   libavcodec     58. 91.100 / 58. 91.100
>   libavformat    58. 45.100 / 58. 45.100
>   libavdevice    58. 10.100 / 58. 10.100
>   libavfilter     7. 85.100 /  7. 85.100
>   libswscale      5.  7.100 /  5.  7.100
>   libswresample   3.  7.100 /  3.  7.100
> Hardware acceleration methods:
> vdpau
> vaapi
> vulkan
> 
> [📦 org.yuzu_emu.yuzu ~]$ 
> ```

Thank you for your report. I am currently investigating why the CUDA support was not correctly included.

**Comment by liushuyu** [comment]
I think I have fixed this issue, try this new build: https://github.com/flathub/org.yuzu_emu.yuzu/pull/221#issuecomment-991510195

**Comment by firig43** [comment]
```
[  24.559349] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:SetTargetCodec:192: NVDEC video codec initialized to VP9
[  24.663060] Service.NVDRV <Info> video_core/command_classes/codecs/codec.cpp:CreateGpuAvDevice:133: Using cuda GPU decoder
```
Thanks for all your work :)

**Comment by liushuyu** [comment]
Thank you! The fix will be merged into yuzu soon.
