### ISSUE TITLE
Add support for Discord Rich Presence

### ISSUE THREAD

**Issue by throwawayn2** [flathub/org.yuzu_emu.yuzu#312]
On AppImage it works

https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by liushuyu** [comment]
In progress in #315

**Comment by liushuyu** [comment]
Closed in #328.

**Comment by pollux56** [comment]
did this feature get added? i dont see it in the settings page

**Comment by Wemmy0** [comment]
This isn't fixed or no longer works
