### ISSUE TITLE
Game Crashes immediately

### ISSUE THREAD

**Issue by Yoshinon42** [flathub/org.yuzu_emu.yuzu#314]
I tried to play Animal Crossing and Slime Rancher and both crash immediatly when trying to Start

the crash screen said that I should attach these thing

inxi -3 shows this:

```
System:    Host: penguin Kernel: 5.4.157-17191-g6575d22de694 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: N/A 
           Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: N/A System: ChromiumOS product: crosvm v: N/A serial: <superuser required> 
           Mobo: N/A model: N/A serial: N/A BIOS: crosvm v: N/A date: N/A 
CPU:       Info: Quad Core model: 06/8c bits: 64 type: MCP arch: Tiger Lake rev: 1 L2 cache: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 23961 
           Speed: 2995 MHz min/max: N/A Core speeds (MHz): 1: 2995 2: 2995 3: 2995 4: 2995 
Graphics:  Device-1: Red Hat Virtio GPU driver: virtio-pci v: N/A bus ID: 00:09.0 
           Display: wayland server: X.Org 1.20.8 driver: loaded: virtio-pci note: n/a (using device driver) 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: virgl v: 4.3 Mesa 20.3.5 direct render: Yes 
Network:   Message: No Device data found. 
           IF-ID-1: eth0 state: up speed: 10000 Mbps duplex: full mac: 00:16:3e:0f:e0:35 
Drives:    Local Storage: total: 55.05 GiB used: 45.96 GiB (83.5%) 
Info:      Processes: 48 Uptime: 58m Memory: 6.49 GiB used: 9.3 MiB (0.1%) Init: systemd runlevel: 5 Compilers: 
           gcc: N/A Packages: 1064 Shell: Bash v: 5.1.4 inxi: 3.3.01
```

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8008825/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8008826/yuzu_log.txt.old.txt)

**Comment by liushuyu** [comment]
Looks like you are running Yuzu inside a Linux virtual machine (`crosvm`) on a ChromeBook.

This is unsupported since current VMs can't support certain advanced graphics API / extensions. What you could do is try to switch to OpenGL + GLSL and see if that works.

**Comment by Yoshinon42** [comment]
Thanks for the Answer

When I switch it to OpenGL it just says this:

Your GPU may not support OpenGL 4.6, or you do not have the latest graphics driver.

GL Renderer:
virgl (Mesa Intel(R) UHD Graphics (TGL GT2))

**Comment by liushuyu** [comment]
Sorry for the late reply, I got caught up in some IRL stuff.

> Do you think it would maybe work with Wine?

No, I don't think so. Yuzu does not use DirectX on Windows, so Wine will just pass through the OpenGL function calls to the host. Although if I happen to be wrong, please correct me here.

In which case, I am sorry you are probably out of options here. The "real" Mesa (not in the VM) will very likely to work, but the one in the virtual machine can't help you very much.

**Comment by liushuyu** [comment]
I am going to close this issue since we can't do much about it. Sorry.
