### ISSUE TITLE
Yuzu never closes in background

### ISSUE THREAD

**Issue by vexusia** [flathub/org.yuzu_emu.yuzu#348]
Hi I am not quite sure how to report this formally but basically I recently noticed alot of my system resources being used and upon checking it turns out that yuzu is not shutting down when closed regardless if a game was ever started or not. 

This was specifically tested when I first installed it on feb 24 2022 (I dont remember build number at the time) in the latest flatpak build at the time, and it was confirmed to shut down when closing, whether it was "x" ing the window or going through the menu under File-exit. 

Now if you quit Yuzu it continues to run in background caching ram until you run a kill command as 'stop' or 'end process' do not effect it. This was done in system-monitor gui in ubuntu 20. Also tested on in multiple clean install virtual machines of different linux distros and on another pc with intel cpu and same issue so Im not sure if its dependent on hardware but it seems extremely easily reproduced based on my testing of it.

Just to confirm this only happens when the program is opened. It does not launch at boot by its own nor is it presistent on reboot.
Steps to reproduce:

-Open yuzu
-Open system-monitor or whatever tracking gui/terminal command to view running processes
-Close yuzu
-Check running processes
       'yuzu' and 'yuzu-launcher' remain running

Opening yuzu again starts another yuzu and yuzu-launcher process with its own ram cache and system resource usage so it continues to compound until you restart the system or manually kill each individual process.

**Comment by hvcrios** [comment]
Yep, same thing happening here

flatpak Yuzu 947, on linux mint 20.3

It started happening like 4 or 5 versions ago, can't say exactly which, but it's fairly recent.

**Comment by vexusia** [comment]
yuzu build 951 updated today seems to fix this, if others can double check the same result then it looks like this can be closed.

**Comment by hvcrios** [comment]
it's fixed here :)

**Comment by liushuyu** [comment]
The issue should have been fixed. Please open a new issue if that is not the case.
