### ISSUE TITLE
pokemon lets go pickachu crash

### ISSUE THREAD

**Issue by 123user123name123** [flathub/org.yuzu_emu.yuzu#420]
walked around in game a little bit then it crashed

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8607959/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8607960/yuzu_log.txt.old.txt)
[inxi_v3.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8607963/inxi_v3.txt)

**Comment by 123user123name123** [comment]
happened again but this time after a long while, game freezes, it doesn't crash. 
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8608182/yuzu_log.txt)

**Comment by liushuyu** [comment]
Sorry for the late reply, we have fixed something in the renderer recently. Can you confirm whether you are still able to replicate the crash in the latest version of yuzu (1108 as of writing).

**Comment by liushuyu** [comment]
Since we did not receive a reply in several months, we have to close this issue.

If your problem still exists after upgrading to the latest yuzu (1286 as of writing), please feel free to open a new issue.
