### ISSUE TITLE
Xenoblade Chronicles 2 Yuzu always crashes after certain cutscene

### ISSUE THREAD

**Issue by phildev4** [flathub/org.yuzu_emu.yuzu#437]
**inxi -v3 output:**

System:
  Host: philipp Kernel: 5.17.5-arch1-1 arch: x86_64 bits: 64 compiler: gcc
    v: 11.2.0 Desktop: KDE Plasma v: 5.24.5 Distro: Arch Linux
Machine:
  Type: Desktop System: Gigabyte product: B550 AORUS ELITE v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B550 AORUS ELITE v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F1
    date: 05/14/2020
Battery:
  Device-1: nintendo_switch_controller_battery_0003:057E:2009.0003 model: N/A
    charge: Full status: full
CPU:
  Info: 12-core model: AMD Ryzen 9 3900XT bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 768 KiB L2: 6 MiB L3: 64 MiB
  Speed (MHz): avg: 2799 high: 4333 min/max: 2200/4776 boost: enabled
    cores: 1: 4101 2: 2101 3: 2084 4: 4333 5: 2064 6: 2121 7: 2195 8: 2195
    9: 2194 10: 2642 11: 3751 12: 3935 13: 3630 14: 2095 15: 2141 16: 3856
    17: 2059 18: 2056 19: 2195 20: 2196 21: 2196 22: 2512 23: 4282 24: 4252
    bogomips: 182132
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: XFX Pine driver: amdgpu v: kernel bus-ID: 0a:00.0
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.1
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    gpu: amdgpu resolution: 1: 2560x1440 2: 1920x1080
  OpenGL: renderer: AMD Radeon RX 580 Series (polaris10 LLVM 13.0.1 DRM
    3.44 5.17.5-arch1-1)
    v: 4.6 Mesa 22.0.3 direct render: Yes
Network:
  Device-1: Realtek RTL8125 2.5GbE vendor: Gigabyte driver: r8169 v: kernel
    port: f000 bus-ID: 08:00.0
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: b4:2e:99:ef:28:0b
Drives:
  Local Storage: total: 1.93 TiB used: 1.23 TiB (63.7%)
Info:
  Processes: 452 Uptime: 1h 43m Memory: 31.35 GiB used: 6.79 GiB (21.7%)
  Init: systemd Compilers: gcc: 12.1.0 clang: 13.0.1 Packages: 1124
  Shell: Bash v: 5.1.16 inxi: 3.3.15

And the log files:
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8672355/yuzu_log.txt)

If you need anything else just ask (:

**Comment by liushuyu** [comment]
We have fixed something in mainline 1105. Are you still experiencing this crash?
