### ISSUE TITLE
Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles issue

### ISSUE THREAD

**Issue by yabb85** [flathub/org.yuzu_emu.yuzu#508]
Hi,

when I try to launch demon slayer game my Yuzu software crash during game loading.

![0100309016e7a000_2022-06-16_21-29-28-564](https://user-images.githubusercontent.com/5111497/174149907-f3d83423-6679-4e88-8905-24f203463af8.png)

following configuration and logs:
[config.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8921859/config.txt)
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/8921847/yuzu_log.txt)

**Comment by liushuyu** [comment]
> ```
> [  49.572020] Debug <Critical> common/host_memory.cpp:operator():408: Assertion Failed!
> mmap failed: Cannot allocate memory
> ```

Can you post the output of `inxi -v3`? This seems like an operating system issue.

**Comment by liushuyu** [comment]
Hi @yabb85,

Are you still experiencing this crash with the latest version of yuzu?

**Comment by yabb85** [comment]
Hi Sorry for the late, I was in holidays.

The output inxi command line is:
```
$inxi -v3
System:    Host: Tofu Kernel: 5.10.0-16-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: GNOME 3.38.6 
           Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Desktop System: Dell product: OptiPlex 7020 v: 01 serial: <superuser required> 
           Mobo: Dell model: 08WKV3 v: A00 serial: <superuser required> UEFI: Dell v: A03 date: 01/08/2015 
CPU:       Info: Quad Core model: Intel Core i5-4590 bits: 64 type: MCP arch: Haswell rev: 3 L2 cache: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 26337 
           Speed: 3497 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 3497 2: 3497 3: 3495 4: 3522 
Graphics:  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] vendor: Sapphire Limited driver: amdgpu 
           v: kernel bus ID: 01:00.0 
           Display: wayland server: X.Org 1.20.11 compositor: gnome-shell driver: loaded: ati,vesa 
           unloaded: fbdev,modesetting,radeon resolution: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX550/550 Series (POLARIS12 DRM 3.40.0 5.10.0-16-amd64 LLVM 11.0.1) v: 4.6 Mesa 20.3.5 
           direct render: Yes 
Network:   Device-1: Intel Ethernet I217-LM vendor: Dell driver: e1000e v: kernel port: f040 bus ID: 00:19.0 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 98:90:96:9c:57:45 
Drives:    Local Storage: total: 1.5 TiB used: 550.7 GiB (36.0%) 
Info:      Processes: 263 Uptime: 2m Memory: 15.57 GiB used: 4.35 GiB (27.9%) Init: systemd runlevel: 5 Compilers: gcc: 10.2.1 
           Packages: 2707 Shell: Zsh v: 5.8 inxi: 3.3.01
```

I try to launch the game with version 1120 (2022-08-02) and the issue is still present.

Thanks

**Comment by yabb85** [comment]
Issue still present on version 1125

**Comment by liushuyu** [comment]
> Issue still present on version 1125

The latest yuzu version (as of writing) is 1255. Can you update your version and try again?

**Comment by yabb85** [comment]
Same issue on 1255
![Capture d’écran de 2022-11-29 22-29-13](https://user-images.githubusercontent.com/5111497/204652150-5a3fcfaf-15e6-43b7-a2fe-a442fcbb8b3e.png)

**Comment by liushuyu** [comment]
We have recently switched to a newer Flatpak runtime which contains a more recent version of the AMD GPU driver (in yuzu 1266). Did this change resolve your issue?

**Comment by yabb85** [comment]
After change my pc and install last Debian version with last version of yuzu the issue is solved.
