### ISSUE TITLE
yuzu crash on emudeck install and startup

### ISSUE THREAD

**Issue by freemj6** [flathub/org.yuzu_emu.yuzu#533]
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9001392/yuzu_log.txt)
only way to fix i have found is a factory reset of deck and install flatpack version.  not ideal if i want to use emudeck for other emus

**Comment by liushuyu** [comment]
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9001392/yuzu_log.txt)
> only way to fix i have found is a factory reset of deck and install flatpack version. not ideal if i want to use emudeck for other emus

Sorry but the log did not capture anything useful. There are now multiple reports related to the EmuDeck, I think I need to contact EmuDeck team to see if something unexpected is introduced in the EmuDeck version of yuzu.

**Comment by liushuyu** [comment]
Sorry, @freemj6, EmuDeck folks told me they no longer use the Flatpak version of yuzu, so I can't provide support for that.

If you have further issues, please report your issues to EmuDeck support channels. If they do not respond to your inquiry, you are welcome to join our Discord server: https://discord.gg/u77vRWY to help us locate the issue for them.

Thank you.
