### ISSUE TITLE
Assertion Failed! Error

### ISSUE THREAD

**Issue by PodcastGuru74** [flathub/org.yuzu_emu.yuzu#583]
[yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9131023/yuzu_log.txt.old.txt)
Hi. I'm trying to run Yuzu on Fedora Linux with KDE, but pretty much every game except Sonic Mania crashes. For example, Mario Party Superstars crashes when I press A to enter the pipe, and Wario Ware: Get It Together crashes once Wario flies in on the screen. I have an AMD Ryzen 7 3700X CPU, an AMD ATI Radeon RX 5600 XT GPU, and 31 GiB of memory, so I am confident the problem is not lack of system resources.
Let me know if you have any other questions about my system, and thanks for the help/making Yuzu better.

**Comment by liushuyu** [comment]
> [yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9131023/yuzu_log.txt.old.txt) Hi. I'm trying to run Yuzu on Fedora Linux with KDE, but pretty much every game except Sonic Mania crashes. For example, Mario Party Superstars crashes when I press A to enter the pipe, and Wario Ware: Get It Together crashes once Wario flies in on the screen. I have an AMD Ryzen 7 3700X CPU, an AMD ATI Radeon RX 5600 XT GPU, and 31 GiB of memory, so I am confident the problem is not lack of system resources. Let me know if you have any other questions about my system, and thanks for the help/making Yuzu better.

Thank you for the report.

We are currently investigating multiple instances of crashes and freezes after some recent changes. Sorry for the inconvenience, and we will update this issue if any progress is made.

Thank you

**Comment by liushuyu** [comment]
Hi there,

We now have a speculative fix for the issue. Since this is a speculative fix, we/I have prepared a test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1189641450.

Please test if this fix at least helps with the crash (e.g. if it delays the crash or makes the crash harder to reproduce).

Thank you

**Comment by liushuyu** [comment]
Hi there,

We now have a new fix for the issue. We have prepared a new test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384.

Please test if this fixes the crash you encountered.

Thank you

**Comment by liushuyu** [comment]
Hi there,

I think your issue should have been fixed in mainline 1105. If not, please help us locate your issue by responding to this comment with your (updated) issue description.

**Comment by liushuyu** [comment]
Hi @PodcastGuru74,

I am not quite sure if you are still experiencing crashes, but I will close this issue soon. If you are still experiencing a crash, please reply to this comment, and I will keep this issue open. Thank you.

**Comment by PodcastGuru74** [comment]
Hi. The issue has been fixed, and I can now play the games I talked about in the original post.
