### ISSUE TITLE
Don't share config with non-flatpak version

### ISSUE THREAD

**Issue by jannuary** [flathub/org.yuzu_emu.yuzu#74]
Currently, yuzu Flatpak stores its data in ~/.config/yuzu, the same directory as the AppImage.

This is discouraged by [Flatpak docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), and it is advised to simply remove `xdg-config/yuzu` and `xdg-data/yuzu` permissions from the manifest.

**Comment by liushuyu** [comment]
Sorry for the late reply. There are users who want to share the data since they have many games inside the data directory.

**Comment by jannuary** [comment]
> Sorry for the late reply. There are users who want to share the data since they have many games inside the data directory.

Sharing data should be opt-in, not opt-out. It shouldn't be a problem to not use xdg-data, since yuzu has options for sd and nand directories.

**Comment by GiantEnemyCrab** [comment]
Just adding a comment here, that I agree with the request. As a flatpak user for other applications, it was surprising to learn of this approach. I think it's also nice to keep in mind about people who would like flatpak stuff to be isolated well from regular installs.

I believe that those who want to share the directory with flatpak vs non-flatpak, then there are options that they can take, including symlink and using an application like flatseal to do some extra configuration to achieve sharing of directory.

I think having isolated envinronment is a key idea for flatpak, and if you can apply that for yuzu flatpak, this behavior will also be consistent with and as expected as other flatpak applications.
