### ISSUE TITLE
What is the reason for filesystem host access? 

### ISSUE THREAD

**Issue by jannuary** [flathub/org.yuzu_emu.yuzu#75]
yuzu has read-only access to the entire host filesystem (`--filesystem=host:ro`), is there any reason for it?
yuzu already seems to support portals, so it is recommended to remove that permission for security reasons.

**Comment by liushuyu** [comment]
> yuzu has read-only access to the entire host filesystem (--filesystem=host:ro), is there any reason for it?

Yes, however, the SDL2 version included in the Flatpak does not support the XDG portal system. So this permission has to stay for now.

Although, I would like to know if anyone is even using the SDL2 version? If not, I am going to remove this permission (also, running the software that is already inside the sandboxed environment using the SDL2 version should be fine though).

**Comment by liushuyu** [comment]
Removed in 0f83cd49a17a72bc099cb394db3e9eabdd16e2ba and will be available in `mainline-0-828`.
