### ISSUE TITLE
[Steam Deck] Games fail to launch with ‘Extended memory layout (6GB DRAM)’ enabled on v1206 and v1205

### ISSUE THREAD

**Issue by gustakasn0v** [flathub/org.yuzu_emu.yuzu#751]
Steps to reproduce:

1. Open yuzu v1206 or v1205
2. Open any game (I’ve tried Super Mario Oddysey, Pokémon Legends Arceus, and Metroid Dread)
3. Notice crash as soon after the shaders finish loading (backtrace and logs attached)

Things I've tried:
- Deleted the shaders cache (`~/.var/app/org.yuzu_emu.yuzu/cache/mesa_shader_cache) and shaders file (`/home/deck/.var/app/org.yuzu_emu.yuzu/data/yuzu/shader/0100000000010000/vulkan.bin`)
- Downgraded to v1204 via `flatpak update -v org.yuzu_emu.yuzu  --commit=23de355ae060efe8e6477e1c1ff7448e8a2215874df1bd53d9c572465d0d16ec` **this fixed my issue**

System info
```
System:
  Host: steamdeck Kernel: 5.13.0-valve21.3-1-neptune arch: x86_64 bits: 64
    compiler: gcc v: 11.1.0 Desktop: KDE Plasma v: 5.23.5 Distro: SteamOS holo
    base: Arch Linux
Machine:
  Type: Portable System: Valve product: Jupiter v: 1
    serial: <superuser required>
  Mobo: Valve model: Jupiter serial: <superuser required> UEFI: Valve
    v: F7A0105 date: 03/21/2022
Battery:
  ID-1: BAT1 charge: 40.1 Wh (98.0%) condition: 40.9/40.0 Wh (102.2%)
    volts: 8.8 min: 7.7 model: MWL32b status: charging
  Device-1: hidpp_battery_2 model: Logitech Wireless Touch Keyboard K400
    charge: 55% (should be ignored) status: discharging
CPU:
  Info: quad core model: AMD Custom APU 0405 bits: 64 type: MT MCP
    arch: Zen 2 rev: 2 cache: L1: 256 KiB L2: 2 MiB L3: 4 MiB
  Speed (MHz): avg: 1411 high: 1576 min/max: 1700/2800 boost: enabled
    cores: 1: 1462 2: 1576 3: 1400 4: 1366 5: 1370 6: 1370 7: 1382 8: 1362
    bogomips: 44822
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD VanGogh driver: amdgpu v: kernel arch: RDNA-2 bus-ID: 04:00.0
    temp: 45.0 C
  Device-2: Logitech C920 PRO HD Webcam type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-1.1:14
  Display: x11 server: X.Org v: 1.21.1.3 with: Xwayland v: 21.1.99 driver:
    X: loaded: amdgpu unloaded: modesetting dri: radeonsi gpu: amdgpu
    resolution: 1: 3440x1440 2: 1280x800~60Hz
  OpenGL: renderer: AMD Custom GPU 0405 (vangogh LLVM 13.0.0 DRM 3.45
    5.13.0-valve21.3-1-neptune) v: 4.6 Mesa 22.0.2 (git-71648faf15)
    direct render: Yes
Network:
  Device-1: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter
    vendor: AzureWave driver: rtw_8822ce v: N/A port: 2000 bus-ID: 03:00.0
  IF: wlan0 state: up mac: 14:13:33:ff:4f:35
  Device-2: Realtek RTL8153 Gigabit Ethernet Adapter type: USB
    driver: r8152 bus-ID: 2-1.3:7
  IF: enp4s0f3u1u3 state: down mac: a0:ce:c8:95:57:29
  Device-3: IMC Networks 802.11ac WLAN Adapter type: USB driver: btusb
    bus-ID: 3-5:3
Drives:
  Local Storage: total: 238.47 GiB used: 196.92 GiB (82.6%)
Info:
  Processes: 316 Uptime: 2h 19m Memory: 14.49 GiB used: 3.6 GiB (24.8%)
  Init: systemd Compilers: gcc: 11.1.0 clang: 13.0.0 Packages: 945
  Shell: Bash v: 5.1.16 inxi: 3.3.22

```
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9844595/yuzu_log.txt)
[yuzu-backtrace.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9844597/yuzu-backtrace.log)

**Comment by gustakasn0v** [comment]
Update: I was able to get the game working by deleting my game-specific emulation settings (`/home/deck/.var/app/org.yuzu_emu.yuzu/config/yuzu/custom/0100000000010000.ini`)

I'm diffing it against the default one to see what caused it, in the meantime i've attached both files
[0100000000010000.ini.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9844640/0100000000010000.ini.txt)
[0100000000010000 faulty.ini.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9844641/0100000000010000.faulty.ini.txt)

**Comment by gustakasn0v** [comment]
I tried enabling them one by one in order, and `use_extended_memory_layout=true` seems to be the culprit

**Comment by gustakasn0v** [comment]
It seems all my games crash when I enable ‘Extended memory layout (6GB DRAM)’. I’ll edit the ticket to reflect this

**Comment by liushuyu** [comment]
> It seems all my games crash when I enable ‘Extended memory layout (6GB DRAM)’. I’ll edit the ticket to reflect this

Thank you for your report! We have fixed this issue in the latest version of yuzu. You can help us confirm it by simply trying it out!

**Comment by liushuyu** [comment]
I will close this since the issue has gone stale. Please feel free to re-open it if the problem persists.
