### ISSUE TITLE
Cannot open nsp files

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [flathub/org.yuzu_emu.yuzu#759]
### yuzu Version

1211

### Description

- Game: Super Mario Odyssey, although it also happens in Mario Kart 8D
- Appimage: not tested
- What was I doing: trying to open Super Mario Odyssey

### System Information

```shell
Linux Mint 21, R3 3100, 32GB Corsair RAM, RX 570 8GB, need anything more?
```

### Logs

[   0.023138] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.023152] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.226643] Frontend <Info> yuzu/main.cpp:GMainWindow:346: yuzu Version: yuzu 1211
[   0.226645] Frontend <Info> yuzu/main.cpp:GMainWindow:362: Host CPU: AMD Ryzen 3 3100 4-Core Processor               | AVX2 | FMA
[   0.226675] Frontend <Info> yuzu/main.cpp:GMainWindow:364: Host OS: KDE Flatpak runtime
[   0.226681] Frontend <Info> yuzu/main.cpp:GMainWindow:365: Host RAM: 31.28 GiB
[   0.226682] Frontend <Info> yuzu/main.cpp:GMainWindow:367: Host Swap: 2.00 GiB
[   0.268691] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File MK8D.nsp has a different type (unknown) than its extension.
[   0.270493] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File Odyssey.nsp has a different type (unknown) than its extension.
[   0.276792] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   0.281591] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File MK8D.nsp has a different type (unknown) than its extension.
[   0.284086] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File Odyssey.nsp has a different type (unknown) than its extension.
[   0.300124] Frontend <Warning> yuzu/main.cpp:SetupPrepareForSleep:1394: QDBusConnection system bus is not connected
[  56.105052] Frontend <Info> yuzu/main.cpp:BootGame:1642: yuzu starting...
[  56.106339] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File Odyssey.nsp has a different type (unknown) than its extension.
[  56.109903] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[  56.109906] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[  56.109907] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[  56.109907] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[  56.109908] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[  56.109908] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[  56.109908] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[  56.109909] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[  56.109916] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[  56.109917] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[  56.109917] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 1
[  56.109918] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[  56.109918] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[  56.109918] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[  56.109919] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[  56.109919] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 1
[  56.109919] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[  56.109920] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 2
[  56.109920] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[  56.109920] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: true
[  56.109921] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 1
[  56.109922] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: true
[  56.109927] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 0
[  56.109928] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: auto
[  56.109928] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[  56.109929] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[  56.109929] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[  56.109930] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/irsu85/.var/app/org.yuzu_emu.yuzu/cache/yuzu
[  56.109930] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/irsu85/.var/app/org.yuzu_emu.yuzu/config/yuzu
[  56.109931] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/irsu85/.var/app/org.yuzu_emu.yuzu/data/yuzu/load
[  56.109931] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/irsu85/.var/app/org.yuzu_emu.yuzu/data/yuzu/nand
[  56.109932] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/irsu85/.var/app/org.yuzu_emu.yuzu/data/yuzu/sdmc
[  56.109932] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs: 
[  56.109933] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[  56.109933] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[  56.109933] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[  56.109934] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[  56.116811] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File Odyssey.nsp has a different type (unknown) than its extension.
[  56.252153] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:472: Device doesn't support float16 natively
[  56.252156] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:479: Device doesn't support viewport swizzles
[  56.252157] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:483: Device doesn't support viewport masks
[  56.252157] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:487: Device doesn't support passthrough geometry shaders
[  56.252158] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:579: Device doesn't support smooth lines
[  56.252158] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:583: Device doesn't support conservative rasterization
[  56.312686] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:740: Blacklisting AMD GCN4 and earlier for VK_EXT_sampler_filter_minmax
[  56.376480] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:184: Driver: radv 21.3.9
[  56.376485] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:185: Device: AMD RADV POLARIS10
[  56.376486] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:186: Vulkan: 1.2.195
[  56.377634] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  56.378701] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  56.383961] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[  56.384677] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.384803] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  56.386430] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.386507] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  56.386705] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.386807] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[  56.387325] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.387402] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[  56.387459] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.387533] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  56.387543] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.387549] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  56.387557] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.391010] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[  56.391152] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.391232] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  56.391508] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.391585] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  56.391781] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.391882] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[  56.391964] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.392041] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[  56.392095] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.392170] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  56.392180] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.392186] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  56.392194] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.392621] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[  56.392636] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.392708] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[  56.392717] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[  56.393205] Core <Critical> core/core.cpp:Load:299: Failed to load ROM (Error 23)!

### Remarks

Maybe similar to https://github.com/yuzu-emu/yuzu/issues/8270

**Comment by liushuyu** [comment]
Did you dump this game from the game card or console internal storage (eShop games)?

**Comment by IrenvanderBeekPXL** [comment]
eshop, but now it's randomly fixed

**Comment by liushuyu** [comment]
> eshop, but now it's randomly fixed

Hmm... So that's fixed, I suppose? Can I close this issue, then? You can re-open it or create a new issue if you reencounter this problem.

**Comment by IrenvanderBeekPXL** [comment]
I don't know, since I did reinitialized the keys, so maybe it's useful for other people if they have the same issue. You can close it though if it helps for order

**Comment by liushuyu** [comment]
Closed for now. Please feel free to open a new issue if the issue happens again.
