### ISSUE TITLE
Boxcat doesnt work

### ISSUE THREAD

**Issue by iMonZ** [flathub/org.yuzu_emu.yuzu#78]
Using Manjaro in a Wayland session with Linux 5.10 the boxcat service doesnt work:

> [  32.038466] Service.BCAT <Error> core/hle/service/bcat/backend/boxcat.cpp:GetStatus:490: Failed to open socket, going offline!

**Comment by liushuyu** [comment]
Boxcat service has been shutted down. Closing.
