### ISSUE TITLE
Crash after loading Pokemon Violet / Legend Arceus {SteamDeck}

### ISSUE THREAD

**Issue by Ultramove** [flathub/org.yuzu_emu.yuzu#807]
Hello,

I tried playing Pokemon Legends Arceus and got black screen, Yuzu froze and only option was to exit the app. 
I was playing games like Super Mario 3D world and Untitled Goose Game which play perfectly, so I think I set it up alright with the prod keys. 

Also tried Pokemon Violet and had same result.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10097135/yuzu_log.txt)

**Comment by liushuyu** [comment]
Hi there,

I am sorry, but can you use the appropriate template for reporting this crash?

![screenshot](https://user-images.githubusercontent.com/6829345/204114488-115242d7-7e00-44e1-9ad7-4f8959b5349d.png)

Thank you!

**Comment by liushuyu** [comment]
Sorry, I have to close this issue due to too little information and not using the correct template.

Please open a new issue with the correct template so that we can identify your problem better.
