### ISSUE TITLE
Mario odyssey Crashes in Bowser's Kingdom, Mushroom Kingdom

### ISSUE THREAD

**Issue by AwakenedMonado** [flathub/org.yuzu_emu.yuzu#809]
### yuzu Version

Yuzu 1248

### Description

Seems to always happen in Bowser's Kingdom when using the electric pathway up to the giant statue.

In the Mushroom Kingdom it happens when doing the Boss rematches, particularly the Desert Kingdom boss with the large hands.

Logs are attached.

### Reproduction Certainty

Not always, but often

### System Information

```shell
System:
  Host: N/A Kernel: 6.0.9-200.fc36.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.37-36.fc36 Desktop: KDE Plasma v: 5.25.5 Distro: Fedora
    release 36 (Thirty Six)
Machine:
  Type: Laptop System: Acer product: Nitro AN515-53 v: V1.28
    serial: <superuser required>
  Mobo: CFL model: Freed_CFS v: V1.28 serial: <superuser required>
    UEFI: Insyde v: 1.28 date: 08/05/2019
Battery:
  ID-1: BAT1 charge: 36.3 Wh (100.0%) condition: 36.3/48.9 Wh (74.2%)
    volts: 16.6 min: 15.2 model: LG PABAS0241231 status: full
  Device-1: wiimote_battery_7c:bb:8a:1c:e2:50 model: N/A charge: N/A
    status: N/A
CPU:
  Info: quad core model: Intel Core i5-8300H bits: 64 type: MT MCP
    arch: Coffee Lake rev: A cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 1783 high: 2301 min/max: 800/2300 cores: 1: 1573
    2: 2300 3: 2300 4: 2264 5: 1132 6: 1128 7: 2301 8: 1273 bogomips: 36799
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] vendor: Acer
    Incorporated ALI driver: i915 v: kernel arch: Gen-9.5 bus-ID: 00:02.0
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: Acer
    Incorporated ALI driver: nvidia v: 520.56.06 arch: Pascal bus-ID: 01:00.0
  Device-3: Quanta HD Webcam type: USB driver: uvcvideo bus-ID: 1-5:3
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.5 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa dri: iris gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa
    22.1.7 direct render: Yes
Network:
  Device-1: Intel Cannon Lake PCH CNVi WiFi driver: iwlwifi v: kernel
    bus-ID: 00:14.3
  IF: wlp0s20f3 state: up mac: b4:6b:fc:15:41:d1
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Acer Incorporated ALI driver: r8169 v: kernel port: 3000
    bus-ID: 07:00.1
  IF: enp7s0f1 state: down mac: 98:28:a6:0e:06:2f
  IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A
Drives:
  Local Storage: total: 2.05 TiB used: 2.44 TiB (119.0%)
Info:
  Processes: 366 Uptime: 5h 21m Memory: 15.46 GiB used: 4.92 GiB (31.8%)
  Init: systemd target: graphical (5) Compilers: gcc: 12.2.1 Packages: 28
  note: see --rpm Shell: Bash v: 5.2.9 inxi: 3.3.22
```

### Logs and Backtraces

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10097346/yuzu_log.txt)

### Remarks

Would be willing to accept alternatives like the appimage version, but running that version would crash anytime I attempted to open the settings.
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10097421/yuzu_log.txt)

Update: New crash, uploading logs.
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10203313/yuzu_log.txt)

**Comment by liushuyu** [comment]
There might be some issues with your game ROM. Can I ask you how you dumped your game? Did you dump it from the game card or it's purchased from eShop?

**Comment by AwakenedMonado** [comment]
Wow that was a fast reply, thanks! This is a dump from the game card.

**Comment by liushuyu** [comment]
> Wow that was a fast reply, thanks! This is a dump from the game card.

Does it come with any DLCs or updates? I think you might need to re-dump your game (together with any DLCs and updates) and see if that solves the problem.

If the problem persists, try uploading another log so that we can take a deeper look.

**Comment by AwakenedMonado** [comment]
The only thing the game comes with is update 1.1. I will definitely update more logs if the problem re-appears, which it most likely will.

**Comment by AwakenedMonado** [comment]
Game crashed again, uploaded new logs. This time it was during the koopa races, forgot that this is a prime time for crashes to happen as well

**Comment by liushuyu** [comment]
We have updated the Flatpak runtime and should have fixed some of the issues surrounding GPU drivers. Please open a new issue if your problem persists.
