### ISSUE TITLE
Yuzu keeps crashing in vulkan settingsOperating 

### ISSUE THREAD

**Issue by rou12nak** [flathub/org.yuzu_emu.yuzu#813]
### yuzu Version

1253

### Description

i have been playing pokemon legends arceus in open gl but now pokemon scarlet has came so i have been trying to play it. in open gl setting it has black screen issues so when i switch to vulkan the emulator crashes plz help me.

### Reproduction Certainty

Always

### System Information

```bash session
Operating System: windows 10 pro 64 bit
CPU: intel core i3 7100 CPU @ 3.90hz
GPU: nvidia gt 710
Game: pokemon violet
```

### Logs and Backtraces

[yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10116994/yuzu_log.txt.old.txt)

**Comment by liushuyu** [comment]
I am sorry but this is not the place for Windows version support. For support for yuzu on Windows, please use our community forum: https://community.citra-emu.org. Thank you.
