### ISSUE TITLE
Black Screen at Pokemon Let's Go Pickachu after choosing controller layout

### ISSUE THREAD

**Issue by badbrain79** [flathub/org.yuzu_emu.yuzu#842]
### yuzu Version

1273

### Description

Started the game Pokemon: Let's Go Pickachu! and selected and confirmed the controller layout. After that nothing happened and I had a black screen.

### System Information

```bash session
Steam Deck
```

### Logs

unfortunately the log file was empty

**Comment by liushuyu** [comment]
> ### System Information
> 
> ```shell
> Steam Deck
> ```
> 
> ### Logs
> 
> unfortunately the log file was empty
> ### Remarks
> 
> _No response_

And unfortunately, this does not give us any useful information regarding your issue. Since Steam Deck is still rolling out quite slowly, not many of our developers have this device on-hand. It may take quite a while to diagnose this problem.
