### ISSUE TITLE
"Open yuzu folder" fails without error message (not reproducible on AppImage)

### ISSUE THREAD

**Issue by Mershl** [flathub/org.yuzu_emu.yuzu#96]
Description:
The "Open yuzu folder" button (below File) fails without an error message on the GUI or terminal. Same mainline version's AppImage does not show this issue.

Tested with yuzu-717.

**Comment by Mershl** [comment]
My bad. This was already mentioned in https://github.com/flathub/org.yuzu_emu.yuzu/issues/6#issuecomment-869063087.

**Comment by liushuyu** [comment]
> Adding a permission for the desired game directory manually (e.g. `~/Games/switch`) makes it work, showing the persistent path and keeps it valid across multiple starts.
> 
> One idea would be to remove the `host:ro` permission and recommend a user to manually add a specific path. Is there a usecase beside the game directories for the `host:ro` permission?

Permission `host:ro` has been removed in 0f83cd49a17a72bc099cb394db3e9eabdd16e2ba.

**Comment by Mershl** [comment]
> Adding a game folder outside of the flatpak e.g. ~/games/switch will be displayed as the following:
image
It happened once now (maybe after a reboot?) that the link became invalid and 0 games were displayed until the folder was readded.

Looking into this. This seems to be the biggest remaining problem. Adding a game directory from outside the flatpak dir will create a temporary mount (/run/user/...). This mount will stay valid for the current run. Restarting yuzu will invalidate this previously added mount. The directory has to be re-added and the cycle repeats.

Creating an invidual `:ro` filesystem permission manually fixes this issue.

New users will be very confused by the temporary mounts vanishing on restart. As this is an issue "by design" the only mitigation would be a flatpak-specific message box on adding game directories recommending adding an filesystem permission for the desired path, restarting yuzu and only then adding the game directory. What do you think?

**Comment by liushuyu** [comment]
> > Adding a game folder outside of the flatpak e.g. ~/games/switch will be displayed as the following:
> > image
> > It happened once now (maybe after a reboot?) that the link became invalid and 0 games were displayed until the folder was readded.
> 
> Looking into this. This seems to be the biggest remaining problem. Adding a game directory from outside the flatpak dir will create a temporary mount (/run/user/...). This mount will stay valid for the current run. Restarting yuzu will invalidate this previously added mount. The directory has to be re-added and the cycle repeats.
> 
> Creating an invidual `:ro` (e.g. `~/dumpedGames/:ro`) filesystem permission fixes this issue.
> 
> New users will be very confused by the temporary mounts vanishing on restart. As this is an issue "by design" the only mitigation would be a flatpak-specific message box on adding game directories recommending adding an filesystem permission for the desired path, restarting yuzu and only then adding the game directory. The Google Chrome flatpak does something similar in mentioning workarounds on specific actions (like installing system extensions). What do you think?

I have tested on my device (KDE 5 + X11), it seems like different DEs implement the portals a bit differently. On KDE, the folder stays mounted even after log-outs and reboots. I am not sure what to do here, though it seems like the most well-known  XDP implementations are `gtk` and `kde` and we could make some assumptions here?

**Comment by liushuyu** [comment]
> The original issue is long fixed. @liushuyu you think the mentioned "side" issues are worthwhile of a separate issue?

Yes, please feel free to open a new issue.
